version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/customs-broker
    depends_on:
      - mongo
    networks:
      - customs-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - customs-network

volumes:
  mongo-data:

networks:
  customs-network:
    driver: bridge